# Generated by Django 5.0.7 on 2024-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('origin_link', models.URLField(unique=True)),
            ],
        ),
    ]
